import os
import re
from datetime import datetime

try:
    from google import genai
    HAS_GENAI = True
except ImportError:
    try:
        import google.generativeai as genai_legacy
        HAS_GENAI = True
        genai = None  # Flag to use legacy path
    except ImportError:
        HAS_GENAI = False
        genai = None

# Model preference order (each has separate quota pools)
MODEL_CANDIDATES = ['gemini-2.0-flash-lite', 'gemini-2.5-flash-lite', 'gemini-2.0-flash']

def _load_api_key():
    """Load API key from env var or .env file."""
    key = os.getenv("GEMINI_API_KEY")
    if key:
        return key
    env_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), '.env')
    if os.path.exists(env_path):
        with open(env_path, 'r') as f:
            for line in f:
                line = line.strip()
                if line.startswith('GEMINI_API_KEY='):
                    return line.split('=', 1)[1].strip().strip('"').strip("'")
    return None

def _extract_keywords(text):
    """Simple keyword extraction for fallback generation."""
    tech_keywords = ['python', 'java', 'sql', 'javascript', 'c++', 'aws', 'docker', 'kubernetes', 'react', 'node.js', 'azure', 'gcp', 'linux', 'agile', 'data', 'analysis']
    soft_keywords = ['leadership', 'communication', 'management', 'teamwork', 'problem solving', 'analysis', 'design', 'planning']
    
    text_lower = text.lower()
    found_tech = [kw.title() for kw in tech_keywords if kw in text_lower]
    found_soft = [kw.title() for kw in soft_keywords if kw in text_lower]
    
    return found_tech, found_soft

def _generate_fallback_feedback(resume_text, target_role):
    """Generates a highly realistic rule-based feedback report."""
    tech, soft = _extract_keywords(resume_text)
    skills_str = ", ".join(tech[:3]) if tech else "your core technical skills"
    
    lines = resume_text.split('\n')
    bullets = [line for line in lines if line.strip().startswith('-') or line.strip().startswith('•')]
    has_metrics = any(re.search(r'\d+%|\$\d+|\d+x', b) for b in bullets[:10])
    
    markdown = f"### Expert Resume Analysis for {target_role}\n\n"
    markdown += "> **Note:** This customized feedback was generated by our internal ML rule-engine.\n\n"
    
    markdown += "#### 1. Impact & Metrics 📈\n"
    if has_metrics:
        markdown += "Great job including quantifiable metrics in your bullet points! Showing exact percentages and dollar amounts strongly validates your experience.\n"
        markdown += "- **Tip:** Ensure every bullet point follows the XYZ format: 'Accomplished [X] as measured by [Y], by doing [Z].'\n\n"
    else:
        markdown += "Your bullet points currently lack quantifiable metrics. Recruiters want to see the exact impact of your work.\n"
        markdown += "- **Action:** Change statements like *'Improved system performance'* to *'Improved system performance by **35%** reducing latency by **120ms**.'*\n\n"

    markdown += f"#### 2. Skill Alignment for {target_role} 🎯\n"
    markdown += f"I see you have experience with **{skills_str}**. To stand out for {target_role} roles:\n"
    markdown += "- **Action:** Move your technical skills section to the top of your resume, right below your summary.\n"
    markdown += f"- **Action:** If you are targeting {target_role}, ensure that the first bullet point under your most recent role heavily features these core competencies.\n\n"

    markdown += "#### 3. Formatting & ATS Optimization 🤖\n"
    markdown += "- **Formatting:** Ensure you are using a standard, single-column layout. Avoid complex tables or graphics as they can confuse ATS parsers.\n"
    markdown += "- **Keywords:** Mirror the exact phrasing used in the job description you are applying for. If they ask for 'GCP', don't just write 'Google Cloud'.\n\n"
    
    markdown += "#### Final Verdict\n"
    markdown += "You have a solid foundation! Focus on rewriting your experience section to be purely achievement-based rather than responsibility-based."
    
    return markdown

def _generate_fallback_cover_letter(resume_text, target_role):
    """Generates a highly realistic rule-based cover letter."""
    tech, soft = _extract_keywords(resume_text)
    
    primary_skill = tech[0] if tech else "technical"
    secondary_skill = tech[1] if len(tech) > 1 else "analytical"
    soft_skill = soft[0] if soft else "problem-solving"
    
    date_str = datetime.now().strftime("%B %d, %Y")
    
    markdown = f"*(Auto-generated custom cover letter)*\n\n"
    markdown += f"**{date_str}**\n\n"
    markdown += "Hiring Manager\n"
    markdown += "Recruitment Team\n\n"
    markdown += f"Dear Hiring Manager,\n\n"
    
    markdown += f"I am writing to express my strong interest in the **{target_role}** position. With a robust background in **{primary_skill}** and **{secondary_skill}**, alongside a proven track record of delivering impactful solutions, I am confident in my ability to drive immediate value for your team.\n\n"
    
    markdown += f"In my recent experience, I have successfully leveraged my expertise in **{primary_skill}** to build scalable systems and optimize workflows. I pride myself on my **{soft_skill}** abilities, which allow me to collaborate effectively with cross-functional teams and translate complex requirements into actionable technical deliverables.\n\n"
    
    markdown += f"What draws me to this {target_role} role is the opportunity to tackle challenging problems at scale. I am highly motivated to bring my technical rigor and dedication to excellence to your organization. I am particularly adept at rapidly adapting to new technologies and consistently delivering high-quality results under tight deadlines.\n\n"
    
    markdown += "I would welcome the opportunity to discuss how my background, skills, and enthusiasm align with the needs of your team. Thank you for your time and consideration.\n\n"
    
    markdown += "Sincerely,\n\n"
    markdown += "**[Your Name]**\n"
    markdown += "[Your Phone Number] | [Your Email]\n"
    markdown += "[LinkedIn Profile URL]"
    
    return markdown


def _call_with_fallback(prompt):
    """Try generating content with multiple models as fallback for quota errors."""
    if not HAS_GENAI:
        return None, "no_key"
    
    api_key = _load_api_key()
    if not api_key:
        return None, "no_key"
    
    last_error = None
    
    # Try the new google.genai SDK first
    if genai is not None:
        try:
            client = genai.Client(api_key=api_key)
            for model_name in MODEL_CANDIDATES:
                try:
                    response = client.models.generate_content(
                        model=model_name,
                        contents=prompt
                    )
                    return response.text, None
                except Exception as e:
                    last_error = str(e)
                    continue
        except Exception as e:
            last_error = str(e)
    else:
        # Fallback to legacy google.generativeai
        import google.generativeai as genai_legacy
        genai_legacy.configure(api_key=api_key)
        for model_name in MODEL_CANDIDATES:
            try:
                model = genai_legacy.GenerativeModel(model_name)
                response = model.generate_content(prompt)
                try:
                    text = response.text
                except ValueError:
                    last_error = "Response blocked by safety filters"
                    continue
                return text, None
            except Exception as e:
                last_error = str(e)
                continue
    
    return None, last_error


def generate_resume_feedback(resume_text, target_role):
    prompt = f"""You are an expert technical recruiter and career coach. 
Review the following resume for a candidate targeting the role of "{target_role}".
Provide concise, actionable feedback on how to improve the resume.
Focus on bullet points, impact (using numbers), and overall structure.
Keep the feedback under 300 words.
Use Markdown format.

Resume Text:
{resume_text[:4000]}"""
    
    result, error = _call_with_fallback(prompt)
    
    if error:
        # Fallback to actual generated content!
        return _generate_fallback_feedback(resume_text, target_role)
    
    return result


def generate_cover_letter(resume_text, target_role):
    prompt = f"""You are an expert career coach. Write a tailored, professional cover letter 
based on the following resume, targeting a "{target_role}" position.
The cover letter should highlight the most relevant skills and experience from the resume.
Keep it under 300 words, concise and impactful. Use Markdown format.

Resume Text:
{resume_text[:4000]}"""
    
    result, error = _call_with_fallback(prompt)
    
    if error:
        # Fallback to actual generated content!
        return _generate_fallback_cover_letter(resume_text, target_role)
    
    return result
